releases:
- name: safe
  version: 0.3.3
  url: https://github.com/cloudfoundry-community/safe-boshrelease/releases/download/v0.3.3/safe-boshrelease-0.3.3.tgz
  sha1: a1bb4bb4c08e20dd088b3f93e6b969a948e1b7bb
