- type: replace
  path: /releases?/name=safe?
  value:
    name:    safe
    version: 0.3.1
    url:     https://github.com/cloudfoundry-community/safe-boshrelease/releases/download/v0.3.1/safe-0.3.1.tgz
    sha1:    ee009da0398ec1688ccfe830d68957be49571b0a

