---
meta:
  ocfp:
    env:
      cloud: (( concat genesis.env "." genesis.type "." ))

params:
  vault_network:       (( concat meta.ocfp.env.cloud "net-vault" ))
  vault_vm_type:       (( concat meta.ocfp.env.cloud "vm-vault" ))
  vault_disk_type:     (( concat meta.ocfp.env.cloud "disk-vault" ))
