platform: linux

image_resource:
  type: registry-image
  source:
    repository: starkandwayne/concourse

inputs:
    - { name: git }
    - { name: git-ci }

run:
  path: git-ci/ci/tasks/release-notes-preview/task
