#!/bin/bash

cd git
if [ -f ci/release_notes.md ]; then
  echo "######   RELEASE NOTES   ###############"
  echo
  cat ci/release_notes.md
  echo
  echo "########################################"
  echo
else
  echo "NO RELEASE NOTES HAVE BEEN WRITTEN"
  echo "You *might* want to do that before"
  echo "hitting (+) on that shipit job..."
  echo
fi
