#!/bin/bash
set -eu

declare -a merge

merge=( manifests/vault.yml
        manifests/releases/safe.yml )

ips="$(lookup params.ips '')"
if [[ -n "$ips" ]] ; then
  instance_count="$(echo "$ips" | jq -r '.|length')"
  (
    cat <<EOF
exodus:
  ips: $ips

instance_groups:
- name: vault
  instances: $instance_count
  networks:
  - name:       (( grab params.vault_network || "vault" ))
    static_ips: $ips
EOF
  ) > manifests/static_ips.yml
  merge+=( manifests/static_ips.yml )
fi

case "$(bosh_cpi)" in
(azure*)
	merge+=( manifests/azure.yml )
	;;
esac

for want in ${GENESIS_REQUESTED_FEATURES}; do
  case "${want}" in 
    (*)
      if [[ -f "${GENESIS_ROOT}/ops/${want}.yml" ]] ; then
        merge+=( "${GENESIS_ROOT}/ops/${want}.yml" )
      else
        abort=1
        describe >&2 \
          "#R{[ERROR]} The #c{$want} feature is invalid. See the manual and ops/ directory for a list of valid features."
      fi
      ;;
  esac
done

echo "${merge[@]}"
