#!/bin/bash
set -eu

declare -a merge
validate_features azure shield

merge=( manifests/vault.yml )

if want_feature azure; then
	merge+=( manifests/azure.yml )
fi
if want_feature shield; then
	merge+=( manifests/shield.yml )
fi

echo "${merge[@]}"
