#!/bin/bash

# Cloud Config checks
if [[ -n "$GENESIS_CLOUD_CONFIG" ]] ; then
  if ! want_feature proto; then
    cloud_config_needs vm_type    $(lookup params.vault_vm_type    default)
    cloud_config_needs network    $(lookup params.vault_network    vault)
    cloud_config_needs disk_type  $(lookup params.vault_disk_pool  default)
    check_cloud_config && describe "  cloud-config [#G{OK}]"
  fi
fi
