#!/bin/bash
set -eu

# Skip auto unseal if auxiliary
prompt_for genesis_vault boolean \
  'Is this your Genesis Vault (for storing deployment credentials)?'

(
echo "---"
echo "kit:"
echo "  name:    $GENESIS_KIT_NAME"
echo "  version: $GENESIS_KIT_VERSION"
echo
echo "params:"
echo "  env: $GENESIS_ENVIRONMENT"

if [ $genesis_vault != "true" ] ; then
  echo "  auxiliary_vault: true"
fi

) >$GENESIS_ROOT/$GENESIS_ENVIRONMENT.yml

offer_environment_editor
