#!/bin/bash
set -eu

# Skip auto unseal if auxiliary
prompt_for genesis_vault boolean \
  'Is this your Genesis Vault (for storing deployment credentials)?'

(
echo "---"
echo "kit:"
echo "  name:    $GENESIS_KIT_NAME"
echo "  version: $GENESIS_KIT_VERSION"
echo

genesis_config_block

if [ $genesis_vault != "true" ] ; then
  echo "params:"
  echo "  auxiliary_vault: true"
else
  echo "params: {}"
fi

) >$GENESIS_ROOT/$GENESIS_ENVIRONMENT.yml
