#!/bin/bash
set -eu

(
echo "---"
echo "kit:"
echo "  name:    $GENESIS_KIT_NAME"
echo "  version: $GENESIS_KIT_VERSION"
echo
echo "params:"
echo "  env: $GENESIS_ENVIRONMENT"

) >$GENESIS_ROOT/$GENESIS_ENVIRONMENT.yml
