#!/bin/bash
set -eu

if [[ $GENESIS_DEPLOY_RC == 0 ]]; then

      echo; echo;
  describe "#M{$GENESIS_ENVIRONMENT} Vault deployed!"
      echo
      echo "For details about the deployment, run"
      echo
  describe "  #G{genesis info $GENESIS_ENVIRONMENT}"
      echo
      echo "Before you can use the Vault, you will need"
      echo "to initialize it first.  To do so, run"
      echo
  describe "  #G{genesis do $GENESIS_ENVIRONMENT init}"
      echo
      echo "If this was not the initial deployment of the"
      echo "Vault, you will need to unseal it, via"
      echo
  describe "  #G{genesis do $GENESIS_ENVIRONMENT unseal}"
      echo
fi
