---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: starkandwayne/concourse

inputs:
- name: git
- name: git-ci
- name: git-latest-tag

run:
  path: git-ci/ci/tasks/spec-check/task
