---
meta:
  kit:     vault
  release: Vault Genesis Kit
  target:  genesis@pipes
  url:     https://pipes.starkandwayne.com
  exposed: yes

  bosh:
    uri:      ((bosh.uri))
    username: ((bosh.username))
    password: ((bosh.password))
    cacert:   ((bosh.ca))

  vault:
    url:       ((vault.url))
    token:     ((vault.token))

  aws:
    access_key: ((aws.access_key_id))
    secret_key: ((aws.secret_access_key))

  github:
    owner:        genesis-community
    repo:         vault-genesis-kit
    branch:       master
    private_key:  ((github.private_key))
    access_token: ((github.access_token))

  shout:
    url:      ((shout.url)
    username: ((shout.username))
    password: ((shout.password))
